name: SecureSDLC Umbrella
run-name: "[Required SecureSDLC Umbrella Workflow] Ref:${{ github.ref_name }}"

on:
  workflow_dispatch: {}
  workflow_call:
    secrets:
      SEMGREP_APP_URL:
        required: true
      SEMGREP_APP_TOKEN:
        required: true
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  securesdlc-visibility-check:
    runs-on: ubuntu-24.04
    outputs:
      visibility: ${{ steps.get_visibility.outputs.visibility }}
    steps:
      - name: Init
        run: |
          echo "securesdlc-test"
          echo ${{ github.ref_name }}
          echo ${{ github.event.repository.default_branch }}

      - name: Get Repository Visibility
        id: get_visibility
        uses: actions/github-script@v6
        with:
          script: |
            const { data: repo } = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            // The 'visibility' field can be 'public', 'private', or 'internal'
            const visibility = repo.visibility;
            console.log(`Repository visibility: ${visibility}`);
            core.setOutput('visibility', visibility);

      - name: Display Visibility
        run: echo "Repository visibility is ${{ steps.get_visibility.outputs.visibility }}"

  securesdlc-sast:
    needs: [securesdlc-visibility-check]
    # if: ${{ needs.securesdlc-visibility-check.outputs.visibility != 'public' }}
    uses: nautilus-wraith/securesdlc-sast/.github/workflows/securesdlc-sast.yml@main
    secrets:
      SEMGREP_APP_URL: ${{ secrets.SEMGREP_APP_URL }}
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  securesdlc-sca:
    needs: [securesdlc-visibility-check]
    # if: ${{ needs.securesdlc-visibility-check.outputs.visibility != 'public' }}
    uses: nautilus-wraith/securesdlc-sast/.github/workflows/securesdlc-sca.yml@main
    secrets:
      SEMGREP_APP_URL: ${{ secrets.SEMGREP_APP_URL }}
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
